### ISSUE TITLE
Ne da se importat v Eclipse

### ISSUE THREAD

**Issue by andrejbauer** [zigazupancic/image-from-circles#1]
Vajinega projekta ne morem importirat v Eclipse, ker repozitorij ne vsebuje datotek od projekta (`.project` in `.classpath` manjkata). A lahko prosim to popravita.

**Comment by jus-kosmac** [comment]
Datoteke od projekta so v mapi Image from circles. Če mislite, da je problem zaradi tega, ker datoteke niso v root direktoriju ampak eno mapo globlje, lahko to popraviva.

**Comment by andrejbauer** [comment]
Ja ne vem, zakaj sem se pritoževal, sorry.
